services:
  - type: web
    name: pdf-resizer
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        gcc \
        libmupdf-dev \
        libfreetype6-dev
      pip install -r requirements.txt
    startCommand: python app.py